server:
  #端口配置
  port: 8080
spring:
  #应用名称
  application:
    name: mybatis-plus
  #数据源配置
  datasource:
    # 驱动不同 mysql 5  com.mysql.jdbc.Driver
    # mysql 8  com.mysql.cj.jdbc.Driver、需要增加时区的配置serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  #配置mybatis-plus日志
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


